# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/salao_agendamentos
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.forward-headers-strategy=framework

# ===================================================================
# ============== CONFIGURAÇÃO DE E-MAIL (PREENCHER!) ==============
# Use um e-mail real. Para o Gmail, gere uma "Senha de App".
# Não use sua senha principal do e-mail aqui.
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gabriel.henrique.0048@gmail.com
spring.mail.password=bpfdofaijmtbcyrj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true